# Generated by Django 3.2 on 2024-10-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='test_inventory',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='test_inventory',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='app113209.test_products'),
        ),
        migrations.AlterField(
            model_name='test_inventory',
            name='warehouse_id',
            field=models.CharField(max_length=50),
        ),
    ]
