# Generated by Django 3.2 on 2024-10-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0002_auto_20241021_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_sales',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='test_sales',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
