# Generated by Django 3.2 on 2024-09-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0002_test_inventory_test_products_test_revenue_test_sales_test_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chart_type', models.CharField(max_length=50)),
                ('data_source', models.CharField(max_length=100)),
                ('x_axis_field', models.CharField(max_length=50)),
                ('y_axis_field', models.CharField(max_length=50)),
                ('filter_condtions', models.JSONField(blank=True, null=True)),
                ('refresh_interval', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='create_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='available',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='modify_id',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='modify_date',
            new_name='modified_date',
        ),
        migrations.AlterField(
            model_name='chart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app113209.branch'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('scatter', 'Scatter Plot'), ('area', 'Area Chart'), ('histogram', 'Histogram'), ('heatmap', 'Heatmap'), ('bubble', 'Bubble Chart'), ('donut', 'Donut Chart'), ('radar', 'Radar Chart'), ('gauge', 'Gauge Chart'), ('funnel', 'Funnel Chart'), ('treemap', 'Treemap'), ('waterfall', 'Waterfall Chart'), ('box', 'Box Plot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
