# Generated by Django 3.2 on 2024-08-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0003_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
