# Generated by Django 3.2 on 2024-11-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0003_auto_20241021_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartconfiguration',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartconfiguration',
            name='ordering',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartconfiguration',
            name='y_axis_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('scatter', 'Scatter Plot'), ('area', 'Area Chart'), ('histogram', 'Histogram'), ('heatmap', 'Heatmap'), {'horizontal_bar', 'Horizontal Bar Chart'}, {'Multi-line Chart', 'multi_line'}, {'combo', 'Combination Chart'}, ('bubble', 'Bubble Chart'), ('donut', 'Donut Chart'), ('radar', 'Radar Chart'), ('gauge', 'Gauge Chart'), ('funnel', 'Funnel Chart'), ('treemap', 'Treemap'), ('waterfall', 'Waterfall Chart'), ('box', 'Box Plot')], max_length=50),
        ),
    ]
