# Generated by Django 3.2 on 2024-09-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0004_user_email_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST_Inventory',
        ),
        migrations.DeleteModel(
            name='TEST_Products',
        ),
        migrations.DeleteModel(
            name='TEST_Revenue',
        ),
        migrations.DeleteModel(
            name='TEST_Sales',
        ),
        migrations.DeleteModel(
            name='TEST_Stores',
        ),
    ]
