# Generated by Django 3.2 on 2024-08-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
