# Generated by Django 3.2 on 2024-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0004_auto_20241113_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartconfiguration',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
