# Generated by Django 3.2 on 2024-09-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0005_auto_20240904_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST_Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TEST_Products',
            },
        ),
        migrations.CreateModel(
            name='TEST_Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TEST_Stores',
            },
        ),
        migrations.CreateModel(
            name='TEST_Sales',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app113209.test_products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app113209.test_stores')),
            ],
            options={
                'db_table': 'TEST_Sales',
            },
        ),
        migrations.CreateModel(
            name='TEST_Revenue',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('revenue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app113209.test_stores')),
            ],
            options={
                'db_table': 'TEST_Revenue',
            },
        ),
        migrations.CreateModel(
            name='TEST_Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app113209.test_products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app113209.test_stores')),
            ],
            options={
                'db_table': 'TEST_Inventory',
            },
        ),
    ]
