# Generated by Django 3.2 on 2024-09-26 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0005_salesdata_stockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartconfiguration',
            old_name='filter_condtions',
            new_name='filter_conditions',
        ),
        migrations.RemoveField(
            model_name='chartconfiguration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chartconfiguration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chartconfiguration',
            name='refresh_interval',
        ),
        migrations.AddField(
            model_name='chartconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 26, 9, 22, 20, 530912, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartconfiguration',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chartconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chartconfiguration',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app113209.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartconfiguration',
            name='x_axis_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chartconfiguration',
            name='y_axis_field',
            field=models.CharField(max_length=100),
        ),
    ]
