# Generated by Django 3.2 on 2024-09-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0005_salesdata_stockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesData',
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
