# Generated by Django 3.2 on 2024-08-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0005_user_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
