# Generated by Django 3.2 on 2024-08-20 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0006_alter_branch_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontsize', models.CharField(default='medium', max_length=10)),
                ('notificationSettings', models.CharField(default='off', max_length=20)),
                ('autoLogin', models.CharField(default='off', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userpreferences',
            },
        ),
    ]
