# Generated by Django 3.2 on 2024-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0006_auto_20240926_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
