# Generated by Django 5.0.6 on 2024-08-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0006_historyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
