# Generated by Django 3.2 on 2024-11-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0004_calendarevent'),
        ('app113209', '0006_alter_chartconfiguration_color'),
    ]

    operations = [
    ]
