# Generated by Django 3.2 on 2024-09-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0006_auto_20240923_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('branch_name', models.CharField(max_length=100)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
    ]
