# Generated by Django 3.2 on 2024-10-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0007_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_sales',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='test_inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='test_inventory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='test_sales',
            name='store',
        ),
        migrations.AddField(
            model_name='test_inventory',
            name='branch_id',
            field=models.ForeignKey(db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app113209.test_stores'),
        ),
        migrations.AddField(
            model_name='test_inventory',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app113209.test_products'),
        ),
        migrations.AddField(
            model_name='test_sales',
            name='branch_id',
            field=models.ForeignKey(db_column='branch_id', default='BR001', on_delete=django.db.models.deletion.CASCADE, to='app113209.test_stores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_inventory',
            name='inventory_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test_inventory',
            name='last_updated',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='test_inventory',
            name='stock_quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test_sales',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='app113209.test_products'),
        ),
    ]
