# Generated by Django 3.2 on 2024-08-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0007_auto_20240823_merged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
