# Generated by Django 3.2 on 2024-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0008_auto_20240821_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='authentication',
            field=models.BooleanField(default='on'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='autoLogin',
            field=models.BooleanField(default='off'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='notificationSettings',
            field=models.BooleanField(default='on'),
        ),
    ]
