# Generated by Django 3.2 on 2024-08-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0007_chart_userhistory_userpreference'),
        ('app113209', '0007_user_failed_attempts_user_is_locked_and_more'),
        ('app113209', '0008_remove_user_is_superuser'),
    ]

    operations = [
    ]
