# Generated by Django 3.2 on 2024-12-03 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0009_userlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlayout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlayout',
            name='layout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterModelTable(
            name='userlayout',
            table='user_layouts',
        ),
    ]
