# Generated by Django 3.2 on 2024-08-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app113209', '0009_merge_20240826_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='device_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='operation_result',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='app113209.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='action',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user'], name='user_histor_user_id_d236a7_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['timestamp'], name='user_histor_timesta_7f64a6_idx'),
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
