# Generated by Django 3.2 on 2024-08-21 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0010_auto_20240821_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart')], max_length=50)),
                ('chart_name', models.CharField(max_length=255)),
                ('chart_data', models.JSONField()),
                ('available', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Chart Name', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app113209.branch')),
                ('create_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charts', to=settings.AUTH_USER_MODEL)),
                ('modify_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charts',
            },
        ),
    ]
