# Generated by Django 3.2 on 2024-08-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0009_merge_20240826_1558'),
        ('app113209', '0011_chart'),
    ]

    operations = [
    ]
