# Generated by Django 3.2 on 2024-08-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0009_merge_20240826_1130'),
        ('app113209', '0013_auto_20240828_1412'),
    ]

    operations = [
    ]
