# Generated by Django 3.2 on 2024-08-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0014_merge_20240828_1657'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='userhistory',
        #     name='device_brand',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userhistory',
        #     name='device_type',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userhistory',
        #     name='operation_result',
        #     field=models.BooleanField(default=True),
        # ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='app113209.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='action',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user'], name='user_histor_user_id_d236a7_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['timestamp'], name='user_histor_timesta_7f64a6_idx'),
        ),
    ]
