# Generated by Django 3.2 on 2024-08-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0015_auto_20240828_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='user_id',
        ),
        # migrations.AddField(
        #     model_name='userhistory',
        #     name='device_brand',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userhistory',
        #     name='device_type',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userhistory',
        #     name='operation_result',
        #     field=models.BooleanField(default=True),
        # ),
    ]
